export const queryKeys = {
  settings: {
    all: ['settings'] as const,
    byCategory: ((category: string) => ['settings', category]) as const,
    key: ((key: string) => ['settings', 'key', key]) as const,
    public: ['settings', 'public'] as const,
  },
  payments: {
    all: ['payments'] as const,
    byInvoice: ((invoiceId: string) => ['payments', invoiceId]) as const,
    pending: ['payments', 'pending'] as const,
  },
  customers: {
    all: ['customers'] as const,
    lists: () => ['customers', 'list'] as const,
    list: (filters: Record<string, any>) => ['customers', 'list', filters] as const,
    details: () => ['customers', 'detail'] as const,
    detail: (id: string) => ['customers', 'detail', id] as const,
  },
  pets: {
    all: ['pets'] as const,
    lists: () => ['pets', 'list'] as const,
    list: (filters: Record<string, any>) => ['pets', 'list', filters] as const,
    details: () => ['pets', 'detail'] as const,
    detail: (id: string) => ['pets', 'detail', id] as const,
    byCustomer: (customerId: string) => ['pets', 'byCustomer', customerId] as const,
    healthTimeline: (petId: string) => ['pets', 'healthTimeline', petId] as const,
  },
  appointments: {
    all: ['appointments'] as const,
    lists: () => ['appointments', 'list'] as const,
    list: (filters: Record<string, any>) => ['appointments', 'list', filters] as const,
    details: () => ['appointments', 'detail'] as const,
    detail: (id: string) => ['appointments', 'detail', id] as const,
    byDate: (date: string) => ['appointments', 'byDate', date] as const,
    byDoctor: (doctorId: string, date: string) => ['appointments', 'byDoctor', doctorId, date] as const,
  },
  products: {
    all: ['products'] as const,
    lists: () => ['products', 'list'] as const,
    list: (filters: Record<string, any>) => ['products', 'list', filters] as const,
    details: () => ['products', 'detail'] as const,
    detail: (id: string) => ['products', 'detail', id] as const,
    lowStock: (branchId?: string) => ['products', 'lowStock', branchId] as const,
    expiringSoon: (days: number, branchId?: string) => ['products', 'expiringSoon', days, branchId] as const,
  },
  invoices: {
    all: ['invoices'] as const,
    lists: () => ['invoices', 'list'] as const,
    list: (filters: Record<string, any>) => ['invoices', 'list', filters] as const,
    details: () => ['invoices', 'detail'] as const,
    detail: (id: string) => ['invoices', 'detail', id] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    unread: ['notifications', 'unread'] as const,
  },
  branches: {
    all: ['branches'] as const,
    current: ['branches', 'current'] as const,
  },
} as const;
