export const DEFAULT_SETTINGS = {
  'general.store_name': { value: 'Petora Petshop', description: 'Nama toko', is_public: true },
  'general.address': { value: '', description: 'Alamat lengkap', is_public: true },
  'general.phone': { value: '', description: 'Nomor telepon', is_public: true },
  'general.email': { value: '', description: 'Email toko', is_public: true },
  'general.logo_url': { value: '', description: 'URL logo', is_public: true },
  'general.operating_hours': {
    value: { open: '08:00', close: '20:00', days: [1, 2, 3, 4, 5, 6] },
    description: 'Jam operasional', is_public: true,
  },
  'general.timezone': { value: 'Asia/Jakarta', description: 'Zona waktu' },
  'general.currency': { value: 'IDR', description: 'Mata uang' },
  'general.language': { value: 'id', description: 'Bahasa default' },
  'general.google_maps_url': { value: '', description: 'Google Maps URL', is_public: true },

  'branches.enabled': { value: false, description: 'Aktifkan multi-cabang' },
  'branches.current_id': { value: null, description: 'Cabang aktif' },

  'tax.ppn_enabled': { value: false, description: 'Aktifkan PPN' },
  'tax.ppn_rate': { value: 11, description: 'Tarif PPN (%)' },
  'tax.pph_enabled': { value: false, description: 'Aktifkan PPh' },
  'tax.pph_rate': { value: 0, description: 'Tarif PPh (%)' },
  'tax.inclusive': { value: false, description: 'Pajak termasuk harga' },
  'tax.tax_id_number': { value: '', description: 'NPWP' },

  'loyalty.enabled': { value: true, description: 'Aktifkan loyalty' },
  'loyalty.points_per_rupiah': { value: 1000, description: 'Rupiah per 1 poin' },
  'loyalty.point_value': { value: 100, description: 'Nilai 1 poin (rupiah)' },
  'loyalty.expiry_months': { value: 12, description: 'Masa berlaku poin' },
  'loyalty.birthday_bonus': { value: true, description: 'Bonus poin ulang tahun' },
  'loyalty.referral_bonus': { value: 100, description: 'Poin bonus referral' },

  'notification.whatsapp_enabled': { value: false, description: 'WhatsApp on' },
  'notification.email_enabled': { value: false, description: 'Email on' },
  'notification.sms_enabled': { value: false, description: 'SMS on' },
  'notification.push_enabled': { value: false, description: 'Push on' },
  'notification.appointment_reminder': { value: true, description: 'Reminder janji' },
  'notification.vaccination_reminder': { value: true, description: 'Reminder vaksin' },
  'notification.grooming_reminder': { value: true, description: 'Reminder grooming' },
  'notification.hotel_reminder': { value: true, description: 'Reminder hotel' },
  'notification.payment_reminder': { value: true, description: 'Reminder bayar' },
  'notification.promotion_broadcast': { value: false, description: 'Broadcast promo' },

  'payment.methods': {
    value: ['CASH', 'TRANSFER', 'QRIS'],
    description: 'Metode pembayaran aktif',
  },
  'payment.gateway_enabled': { value: false, description: 'Gateway on' },
  'payment.gateway_provider': { value: '', description: 'Provider' },
  'payment.gateway_config': { value: {}, description: 'Config gateway' },
  'payment.manual_instructions': {
    value: { bank_name: '', account_number: '', account_holder: '', qr_image_url: '' },
    description: 'Instruksi manual',
  },
  'payment.split_payment': { value: true, description: 'Izinkan split payment' },
  'payment.partial_payment': { value: true, description: 'Izinkan bayar parsial' },

  'printer.receipt_enabled': { value: true, description: 'Cetak struk' },
  'printer.barcode_enabled': { value: true, description: 'Cetak barcode' },
  'printer.thermal_printer': { value: false, description: 'Thermal printer' },
  'printer.paper_size': { value: '80mm', description: 'Ukuran kertas' },
  'printer.auto_print': { value: true, description: 'Auto cetak' },
  'printer.label_printer': { value: false, description: 'Label printer' },
  'printer.label_size': { value: '50x30mm', description: 'Ukuran label' },

  'reminder.vaccination_days_before': { value: 7, description: 'H- reminder vaksin' },
  'reminder.grooming_interval_days': { value: 30, description: 'Interval grooming' },
  'reminder.hotel_checkin_hours_before': { value: 24, description: 'H- check-in' },
  'reminder.appointment_hours_before': { value: 2, description: 'H- appointment' },
  'reminder.expiry_days_before': { value: 30, description: 'H- expiry produk' },
  'reminder.low_stock_threshold': { value: 10, description: 'Threshold low stock' },

  'receipt.header_text': { value: 'Terima kasih!', description: 'Header struk' },
  'receipt.footer_text': { value: 'Simpan struk ini', description: 'Footer struk' },
  'receipt.show_logo': { value: true, description: 'Tampilkan logo' },
  'receipt.show_tax_id': { value: false, description: 'Tampilkan NPWP' },
  'receipt.show_qr_code': { value: false, description: 'QR di struk' },
  'receipt.show_loyalty_points': { value: true, description: 'Tampilkan poin' },
  'receipt.show_barcode': { value: true, description: 'Barcode invoice' },
  'receipt.template': { value: 'default', description: 'Template struk' },

  'security.session_timeout': { value: 30, description: 'Timeout sesi (menit)' },
  'security.pin_length': { value: 6, description: 'Panjang PIN' },
  'security.max_failed_attempts': { value: 5, description: 'Max gagal login' },
  'security.lockout_duration': { value: 15, description: 'Durasi lockout' },
  'security.require_2fa': { value: false, description: 'Wajib 2FA' },
  'security.ip_whitelist': { value: [], description: 'IP whitelist' },
  'security.password_policy': {
    value: { min_length: 8, require_uppercase: true, require_number: true },
    description: 'Kebijakan password',
  },

  'integration.fonnte_token': { value: '', description: 'Token Fonnte' },
  'integration.fonnte_device': { value: '', description: 'Device Fonnte' },
  'integration.resend_api_key': { value: '', description: 'API key Resend' },
  'integration.from_email': { value: 'noreply@petora.app', description: 'Email pengirim' },
  'integration.sms_gateway': { value: '', description: 'SMS gateway' },
  'integration.sms_api_key': { value: '', description: 'SMS API key' },
  'integration.midtrans_server_key': { value: '', description: 'Midtrans server key' },
  'integration.midtrans_client_key': { value: '', description: 'Midtrans client key' },

  'backup.auto_enabled': { value: true, description: 'Auto backup' },
  'backup.schedule': { value: '02:00', description: 'Jam backup' },
  'backup.retention_days': { value: 30, description: 'Retensi backup' },
  'backup.include_storage': { value: false, description: 'Backup storage' },

  'employee.commission_enabled': { value: true, description: 'Komisi aktif' },
  'employee.commission_type': { value: 'percentage', description: 'Tipe komisi' },
  'employee.commission_rate': { value: 5, description: 'Rate komisi (%)' },
  'employee.performance_tracking': { value: true, description: 'Tracking performa' },

  'subscription.enabled': { value: false, description: 'Subscription aktif' },
  'subscription.auto_renewal': { value: true, description: 'Auto renew' },
  'subscription.grace_period_days': { value: 3, description: 'Grace period' },

  'delivery.enabled': { value: false, description: 'Delivery aktif' },
  'delivery.zones': { value: [], description: 'Zona delivery' },
  'delivery.pricing_type': { value: 'flat', description: 'Tipe harga' },
  'delivery.free_minimum': { value: 0, description: 'Min gratis ongkir' },
  'delivery.courier_integration': { value: '', description: 'Integrasi kurir' },

  'inventory.costing_method': { value: 'AVERAGE', description: 'Metode costing' },
  'inventory.auto_reorder': { value: false, description: 'Auto reorder' },
  'inventory.batch_tracking': { value: true, description: 'Batch tracking' },
  'inventory.expiry_tracking': { value: true, description: 'Expiry tracking' },
  'inventory.serial_tracking': { value: false, description: 'Serial tracking' },
  'inventory.warehouses': { value: ['main'], description: 'Daftar gudang' },

  'custom_fields.customer': { value: [], description: 'Custom fields customer' },
  'custom_fields.pet': { value: [], description: 'Custom fields pet' },

  'advanced.debug_mode': { value: false, description: 'Debug mode' },
  'advanced.maintenance_mode': { value: false, description: 'Maintenance' },
  'advanced.analytics_enabled': { value: true, description: 'Analytics on' },
  'advanced.telemetry': { value: false, description: 'Telemetry' },
} as const;

export type DefaultSettingsKey = keyof typeof DEFAULT_SETTINGS;
